- hosts: localhost
  remote_user: "{{ ansible_centos_user }}"
  sudo: true
  gather_facts: true

  vars:
    transfer_method: copy-from-controller

  roles:
  - jboss_common
  - jboss_eap
  - jboss_bxms
